fix(aot): AOT build failing after adding string data support
ERROR in ../angular-bootstrap-datetimepicker/angular-bootstrap-datetimepicker.ts(104,9): Error
during template compile of 'DlDateTimePickerStringModule’. Function calls are not supported in
decorators but 'localeData' was called.

Fixes #429